version: 2.1

jobs:
  run-script:
    docker:
      # Use a Node.js image
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Script
          command: node kolo.js

workflows:
  version: 2
  run-workflow:
    jobs:
      - run-script
